"use client";
import {useState} from 'react';
const questions=[{key:'firstName',label:'What is your first name?',type:'text',complete:'given-name',required:true},{key:'lastName',label:'What is your last name?',type:'text',complete:'family-name',required:true},{key:'email',label:'Which email should we use?',type:'email',complete:'email',required:true},{key:'phone',label:'What is your mobile number?',type:'tel',complete:'tel',required:false},{key:'password',label:'Choose your password',type:'password',complete:'new-password',required:true}] as const;
export default function GuidedRegistration(){
 const [values,setValues]=useState({firstName:'',lastName:'',email:'',phone:'',password:''}),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();if(step<questions.length){setStep(s=>s+1);return;}setBusy(true);setError('');try{const r=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,phone:values.phone||undefined}),signal:AbortSignal.timeout(15000)});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Your profile could not be created. Check your details or retry.');window.location.assign('/');}catch(e){setError(e instanceof Error?e.message:'Registration was interrupted. Check your details and retry.');}finally{setBusy(false);}}
 const question=questions[step];
 return <form onSubmit={submit}><p className="access-note" role="status">{step<questions.length?`Question ${step+1} of ${questions.length}`:'Review your details'}</p><div className="registration-progress" aria-hidden="true"><span style={{width:`${(step+1)/(questions.length+1)*100}%`}}/></div>{question?<label className="field"><span>{question.label}</span><input className="input" key={question.key} name={question.key} type={question.type} autoComplete={question.complete} autoFocus required={question.required} minLength={question.key==='password'?10:undefined} pattern={question.key==='password'?'(?=.*[A-Za-z])(?=.*[0-9]).{10,}':undefined} value={values[question.key]} onChange={e=>setValues({...values,[question.key]:e.target.value})}/>{question.key==='password'&&<small className="access-note">At least 10 characters, including a letter and a number.</small>}{question.key==='phone'&&<small className="access-note">Optional. Include your country code.</small>}</label>:<dl className="registration-review"><dt>Name</dt><dd>{values.firstName} {values.lastName}</dd><dt>Email</dt><dd>{values.email}</dd><dt>Mobile</dt><dd>{values.phone||'Not provided'}</dd><dt>Password</dt><dd>Provided securely</dd></dl>}
 {error&&<div className="access-error" role="alert"><p>{error}</p><button type="button" onClick={()=>{setStep(0);setError('');}}>Edit details</button><button type="button" onClick={()=>setError('')}>Dismiss</button></div>}<div className="registration-actions">{step>0&&<button type="button" className="registration-back" disabled={busy} onClick={()=>setStep(s=>s-1)}>Back</button>}<button className="btn block" disabled={busy}>{busy?'Creating your profile…':question?'Continue':'Create profile'}</button></div><p className="alt"><a href="/login">{step?'Cancel · Return to sign-in':'Already with us? Sign in'}</a></p></form>;
}
