"use client";
import {useEffect,useState} from 'react';
type Preferences={phone:string|null;preferredLanguage:string;preferredTheme:string};
export default function ProfileSettings(){
 const [user,setUser]=useState<Preferences|null>(null),[phone,setPhone]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[branches,setBranches]=useState<{id:string;name:string;address:string;city:string;hours:string|null;distanceKm:number|null}[]|null>(null);
 async function load(){try{const r=await fetch('/api/me',{cache:'no-store',signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Settings could not be loaded.');setUser(d.user);setPhone(d.user.phone||'');}catch(e){setMessage(e instanceof Error?e.message:'Settings could not be loaded.');}}
 useEffect(()=>{void load();},[]);
 async function findBranches(){const load=async(q='')=>{try{const r=await fetch('/api/branches'+q,{signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw Error(data.error||'Locations could not be loaded.');setBranches(data);}catch(e){setMessage(e instanceof Error?e.message:'Locations could not be loaded. Retry.');}};if(!navigator.geolocation)return void load();navigator.geolocation.getCurrentPosition(p=>void load('?lat='+p.coords.latitude+'&lng='+p.coords.longitude),()=>void load(),{timeout:8000});}
 async function save(patch:Record<string,string>){setBusy(true);setMessage('');try{const r=await fetch('/api/me',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Settings could not be saved.');if(patch.preferredTheme)document.documentElement.setAttribute('data-theme',patch.preferredTheme);await load();setMessage('Preferences saved.');}catch(e){setMessage(e instanceof Error?e.message:'Settings could not be saved.');}finally{setBusy(false);}}
 return <section id="settings" aria-labelledby="profile-settings-title"><h2 id="profile-settings-title">Settings &amp; security</h2><p>Your banking preferences and account protection, in one place.</p>{message&&<p role="status">{message} {!user&&<button type="button" className="profile-edit" onClick={()=>void load()}>Retry</button>}</p>}{user&&<><div className="profile-question"><label htmlFor="bank-phone">Banking mobile number</label><input id="bank-phone" type="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)}/><button type="button" className="profile-edit" disabled={busy} onClick={()=>void save({phone})}>Save number</button></div><div className="profile-question"><label htmlFor="bank-language">Citizen AI language</label><select id="bank-language" value={user.preferredLanguage} disabled={busy} onChange={e=>void save({preferredLanguage:e.target.value})}><option value="en">English</option><option value="st">Sesotho</option><option value="zu">isiZulu</option></select><label htmlFor="bank-theme">Appearance</label><select id="bank-theme" value={user.preferredTheme} disabled={busy} onChange={e=>void save({preferredTheme:e.target.value})}><option value="dark">Dark</option><option value="light">Light</option></select></div><button type="button" className="profile-edit" onClick={()=>window.dispatchEvent(new Event('citizen:security-settings'))}>Manage secure unlock &amp; account checks</button><p><a href="https://hub.citizenbank.co.ls/reset-password">Reset shared Citizen password</a></p><button type="button" className="profile-edit" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('Sign-out failed. Retry.');window.location.replace('/login');}catch(e){setMessage(e instanceof Error?e.message:'Sign-out failed.');setBusy(false);}}}>Sign out</button><section id="help"><h3>Help &amp; planned locations</h3><p>Citizen Bank is in pre-licensing. Listed locations are planning references; banking transactions remain demonstrations.</p><button className="profile-edit" type="button" onClick={()=>void findBranches()}>Find planned locations</button>{branches?.map(b=><p key={b.id}><strong>{b.name}</strong><br/>{b.address}, {b.city}{b.hours?' · '+b.hours:''}{b.distanceKm!==null?' · '+b.distanceKm+' km':''}</p>)}</section></>}</section>;
}
