"use client";
import { useEffect, useState } from "react";
type Shared = {linked:boolean;roles:string[];profile?:Record<string,unknown>};
const common=[['full_name','Full name'],['phone','Phone'],['street_address','Street address'],['city','City'],['country','Country'],['occupation','Occupation'],['employer','Employer'],['bio','About me']];
const investor=[['source_of_funds','Source of funds'],['investor_type','Investor type'],['investment_purpose','Investment purpose']];
export default function SharedProfile(){
 const [data,setData]=useState<Shared|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState('');
 const [editing,setEditing]=useState<string|null>(null);
 const [values,setValues]=useState<Record<string,string>>({});
 async function load(){setError('');try{const r=await fetch('/api/profile',{cache:'no-store'});if(!r.ok)throw new Error('Your shared profile is unavailable. Please try again.');const d=await r.json();setData(d);setValues(Object.fromEntries([...common,...investor].map(([key])=>[key,String(d.profile?.[key]??'')])));}catch(e){setError(e instanceof Error?e.message:'Profile unavailable');}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!data?.profile)return;setBusy(true);setError('');setSaved('');try{const fields=[...common,...(data.roles.some(r=>['investor','shareholder'].includes(r))?investor:[])];const patch: Record<string, unknown>=Object.fromEntries(fields.filter(([key])=>values[key]!==String(data.profile?.[key]??'')).map(([key])=>[key,values[key]]));if(!Object.keys(patch).length){setSaved('No changes to save.');return;}patch.version=data.profile.version;const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});if(!r.ok)throw new Error(r.status===409?'Your profile changed elsewhere. Reload before saving.':'Your profile could not be saved.');await load();setSaved('Profile saved across your Citizen roles.');}catch(e){setError(e instanceof Error?e.message:'Unable to save');}finally{setBusy(false);}}
 return <section className='citizen-profile'><h1>My Citizen profile</h1><p>One identity, with details for each of your roles.</p><p><a href={(process.env.NEXT_PUBLIC_HUB_URL || "https://citizen-hub-demo.vercel.app")+"/opportunities"}>Explore investment opportunities and subscribe for shares ↗</a></p><p><a href='/'>Back to banking</a> · <a href={process.env.NEXT_PUBLIC_WEBSITE_URL || 'https://citizenbank.co.ls/'}>Citizen Bank website</a></p>{error&&<p role='alert'>{error} <button type='button' onClick={()=>{setError('');void load();}}>Retry</button></p>}{saved&&<p role='status'>{saved}</p>}{!data&&!error&&<p role='status'>Loading profile…</p>}{data&&!data.linked&&<p>This banking profile has not yet been linked to a Citizen platform identity. Manage your customer preferences in Settings.</p>}{data?.profile&&<form onSubmit={save}><p>Roles: {data.roles.map(r=>r.replaceAll('_',' ')).join(', ')}</p>{[['Shared identity',common],...(data.roles.some(r=>['investor','shareholder'].includes(r))?[['Investor details',investor]]:[])].map(([title,fields])=><fieldset key={title as string} style={{minWidth:0,margin:'20px 0',padding:16,border:'1px solid currentColor'}}><legend>{title as string}</legend>{(fields as string[][]).map(([key,label])=><div key={key} className='profile-item'><div><strong>{label}</strong><p>{values[key]||'Not supplied'}</p></div><button type='button' className='profile-edit' onClick={()=>setEditing(key)}>Edit {label.toLowerCase()}</button>{editing===key&&<div className='profile-question'><label htmlFor={'profile-'+key}>What is your {label.toLowerCase()}?</label><input autoFocus id={'profile-'+key} value={values[key]||''} onChange={e=>setValues({...values,[key]:e.target.value})}/><button type='button' className='profile-edit' onClick={()=>setEditing(null)}>Done</button></div>}</div>)}</fieldset>)}{data.roles.includes('customer')&&<p>Customer account preferences, security and KYC are managed in this banking system.</p>}{data.roles.includes('board_member')&&<p><a href={(process.env.NEXT_PUBLIC_HUB_URL || 'https://citizen-hub-demo.vercel.app')+'/profile'}>Manage board member details</a></p>}<button className='btn' disabled={busy}>{busy?'Saving…':'Save profile'}</button></form>}</section>;
}
